language: python


python:
  - "3.8"

dist: xenial

sudo: false

services:
  - docker

before_install:
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - if [[ -n "$DOCKERHUB_PASSWORD" && -n "$DOCKERHUB_USERNAME" ]]; then echo "logining in to docker";echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin;fi
  - bash -x start_ocean.sh --no-dashboard 2>&1 > start_ocean.log &
  - cd ..
  - |
      for i in $(seq 1 150); do
        sleep 6
        [ -f "${HOME}/.ocean/ocean-contracts/artifacts/ready" ] && break
      done
      ls -la "${HOME}/.ocean/ocean-contracts/artifacts/"

install: pip install -U tox-travis

script: tox

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/ocean.py
    python: 3.8
