##
## Copyright 2021 Ocean Protocol Foundation
## SPDX-License-Identifier: Apache-2.0
##
language: python


python:
  - "3.8"

dist: xenial

sudo: false

services:
  - docker

env:
  global:
    - CC_TEST_REPORTER_ID=3f0e12c83401974ee46f5d1b37beeb818f5acadcd5f7f647d217cd9473c15371

before_install:
  - git clone https://github.com/oceanprotocol/barge
  - cd barge
  - export PROVIDER_VERSION=secure_outputs
  - if [[ -n "$DOCKERHUB_PASSWORD" && -n "$DOCKERHUB_USERNAME" ]]; then echo "logging in to docker";echo "$DOCKERHUB_PASSWORD" | docker login -u "$DOCKERHUB_USERNAME" --password-stdin;fi
  - bash -x start_ocean.sh --no-dashboard --with-provider2  2>&1 > start_ocean.log &
  - cd ..
  - |
      for i in $(seq 1 150); do
        sleep 6
        [ -f "${HOME}/.ocean/ocean-contracts/artifacts/ready" ] && break
      done
      ls -la "${HOME}/.ocean/ocean-contracts/artifacts/"

install: pip install -U tox-travis

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script: tox

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT

deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: ${PYPI_USER}
  password: ${PYPI_PASSWORD}
  on:
    tags: true
    repo: oceanprotocol/ocean.py
    python: 3.8
